# Book settings
title: CHORDS Data Tutorial
author: Keith Maull, Agbeli Ameko, Mike Daniels & Mike Dye; Logo image <a href="https://www.freepik.com/free-vector/infinity-colorful-logo-gradient_30697739.htm#page=3&query=logo%20png%20mobius&position=32&from_view=search&track=ais#position=32&page=3&query=logo%20png%20mobius">by logturnal on Freepik</a>
logo: logo.png
copyright: "2023" 

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

bibtex_reference_style: author_year 